language: ruby
cache: bundler

rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

#before_install:
#  - gem update --system
#  - gem install bundler

gemfile:
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_master.gemfile

matrix:
  fast_finish: true
  # Run Danger only once
  include:
    - rvm: 2.5
      gemfile: gemfiles/rails_5_2.gemfile
      script: bundle exec danger
  exclude:
    - gemfile: gemfiles/rails_6_0.gemfile
      rvm: 2.4
    - gemfile: gemfiles/rails_master.gemfile
      rvm: 2.4
  allow_failures:
    - gemfile: gemfiles/rails_master.gemfile
    - rvm: ruby-head
