cache: bundler
language: ruby
sudo: false

rvm:
  - 2.1
  - 2.2.4
  - 2.3.0

before_install:
  - gem install bundler -v '~> 1.10'

env:
  - rails=4.2.0
  - rails=5.0.0.rc1

matrix:
  exclude:
    - env: rails=5.0.0.rc1
      rvm: 2.1
