language: ruby
sudo: false
cache: bundler

rvm:
  - 2.0
  - 2.1

env:
  - rails=3.2.0
  - rails=4.1.0
  - rails=4.2.0

gemfile:
  - Gemfile
  - gemfiles/Gemfile.mongoid2.rb
  - gemfiles/Gemfile.mongoid3.rb
  - gemfiles/Gemfile.mongoid4.rb
  - gemfiles/Gemfile.mongo_mapper.rb

services:
  - mongodb

matrix:
  exclude:
    - gemfile: gemfiles/Gemfile.mongoid2.rb
      env: rails=4.1.0
    - gemfile: gemfiles/Gemfile.mongoid2.rb
      env: rails=4.2.0

    - gemfile: gemfiles/Gemfile.mongoid3.rb
      env: rails=4.1.0
    - gemfile: gemfiles/Gemfile.mongoid3.rb
      env: rails=4.2.0

    - gemfile: gemfiles/Gemfile.mongoid4.rb
      env: rails=3.2.0
