language: ruby
before_install:
  - gem install bundler -v '= 1.5.1'
rvm:
  - 1.9.3
  - 2.0
  - 2.1
env:
  - rails=3.1.8
  - rails=3.2.8
  - rails=3.2.16
  - rails=4.0.2
  - rails=4.1.0.beta1
  - orm=mongoid2
  - orm=mongoid3
  - orm=mongoid4
  - orm=mongo_mapper
  - table_name_prefix=h_
  - table_name_suffix=_h
services:
  - mongodb
